name: Auto Create Pull Request

on:
  push:
    branches:
      - 'feature/*'  # Trigger the workflow when code is pushed to any feature branch

jobs:
  create_pull_request:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
      
      - name: Install GitHub CLI
        run: |
          sudo apt update
          sudo apt install gh -y
      
      - name: Authenticate with GitHub CLI
        run: |
          gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      - name: Create Pull Request
        run: |
          # Get the current branch name
          BRANCH_NAME=$(git symbolic-ref --short HEAD)
          
          # Create a pull request from the current branch to develop
          gh pr create --title "Auto PR from $BRANCH_NAME" \
            --body "This PR was created automatically by GitHub Actions." \
            --head "$BRANCH_NAME" \
            --base develop \
